apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: hotrod 
    namespace: hotrod 
    labels:
      app: hotrod 
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: hotrod 
      spec:
          containers:
          -   env:
              - name: JAEGER_AGENT_HOST 
                value: jaeger-agent.observability.svc.cluster.local
              - name: JAEGER_AGENT_PORT
                value: "6831"
              #image: jaegertracing/example-hotrod:latest
              image: 847553930390.dkr.ecr.ap-northeast-1.amazonaws.com/hotrod/hotrod-github:latest 
              name: hotrod 
              ports:
                - containerPort: 8080
                  protocol: TCP
                - containerPort: 8081
                  protocol: TCP
                - containerPort: 8082
                  protocol: TCP
                - containerPort: 8083
                  protocol: TCP

- apiVersion: v1
  kind: Service
  metadata:
    name: hotrod 
    namespace: hotrod
    labels:
      app: hotrod 
  spec:
    ports:
      - name: port0
        port: 80
        protocol: TCP
        targetPort: 8080 
      - name: port1
        port: 8081
        protocol: TCP
        targetPort: 8081
      - name: port2
        port: 8082
        protocol: TCP
        targetPort: 8082 
      - name: port3
        port: 8083
        protocol: TCP
        targetPort: 8083
    selector:
      app: hotrod
    type: LoadBalancer
