name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on: [push]

jobs: 
  build: 
    name: Greeting
    runs-on: ubuntu-latest
    steps: 
      - name: "setup go"
        uses: actions/checkout@master
      - name: "unit test"
        uses: actions/setup-go@v1 
        run: "go test ./..."
        with: 
          go-version: 1.12
#      - name: "docker build and push"
#        run: "docker build . --file Dockerfile --tag hotrod:$(date +%s)"
#        uses: actions/docker-build-and-push@v1
