name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on: [push]

jobs: 
  build: 
    name: Greeting
    runs-on: ubuntu-latest
    steps: 
      - name: "checkout go"
        uses: actions/checkout@master
      - name: "setup go"
        uses: actions/setup-go@v1
        with:
          go-version: '1.12'
      - name: "go test" 
        run: export GOPATH=${PWD}; cd services; go test ./...
      - name: "docker build and push"
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: hotrod 
#        run: docker build . --file Dockerfile --tag hotrod:$(date +%s)
#        uses: actions/docker-build-and-push@v1
#        uses: "actions/docker/cli@c08a5fc9e0286844156fefff2c141072048141f6"
#        run: /bin/sh -c docker build -t $IMAGE_URI .
#        env: 
#          IMAGE_URI: "hotrod:test"
